# Generated by Django 6.0 on 2025-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emaillogincode_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillogincode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
