# Generated by Django 6.0 on 2026-01-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.TextField(default='a', max_length=500),
            preserve_default=False,
        ),
    ]
