# Generated by Django 6.0 on 2026-04-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
    ]
