# Generated by Django 6.0 on 2026-05-08 17:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_akcii_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
