# Generated by Django 6.0 on 2025-12-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_session_id_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
