# Generated by Django 6.0 on 2026-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='actual_price',
            field=models.FloatField(default=850),
            preserve_default=False,
        ),
    ]
