# Generated by Django 6.0 on 2026-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_actual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='actual_price',
        ),
    ]
