# Generated by Django 6.0 on 2026-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Shipped'), (3, 'Cancelled')], default=0),
        ),
    ]
