# Generated by Django 6.0 on 2026-02-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('self', 'Self'), ('courier', 'Courier')], default='self'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='testName', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='testSurname', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='pending'),
        ),
    ]
